name: workflow for S3 Deploy
on:
  push:
    branches:
      - develop
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build dev
        run: yarn build:dev
        if: contains(github.ref, 'develop')

      - name: Build prod
        run: yarn build:prdo
        if: contains(github.ref, 'main')

      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: build
          bucket: ${{ secrets.S3_BUCKET_DEV }}
          bucket-region: ap-northeast-2
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_DEV }}
          invalidation: /*
          delete-removed: true
          no-cache: true
          private: true
