name: workflow for S3 Deploy Develop
on:
  push:
    branches:
      - develop
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REACT_APP_CHECKIN_API_URL: ${{secrets.REACT_APP_CHECKIN_API_URL_DEV}}
      REACT_APP_VISITOR_API_URLL: ${{secrets.REACT_APP_VISITOR_API_URL_DEV}}
      REACT_APP_X_42CADET_CHECKIN_AUTH_KEY: ${{secrets.REACT_APP_X_42CADET_CHECKIN_AUTH_KEY}}
      REACT_APP_X_42CADET_VISITOR_AUTH_KEY: ${{secrets.REACT_APP_X_42CADET_VISITOR_AUTH_KEY}}
      REACT_APP_VERSION: ${{secrets.REACT_APP_VERSION}}
      REACT_APP_AUTH_KEY: ${{secrets.REACT_APP_AUTH_KEY_DEV}}
      
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build dev
        run: yarn build:dev

      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: build
          bucket: ${{ secrets.S3_BUCKET_DEV }}
          bucket-region: ap-northeast-2
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_DEV }}
          invalidation: /*
          delete-removed: true
          no-cache: true
          private: true
